dist:
  name: qubership-otec
  description: Custom OTel Collector for qubership platform
  module: github.com/Netcracker/qubership-open-telemetry-collector
  version: 1.1.25
  output_path: ./collector

connectors:
  - gomod: github.com/Netcracker/qubership-open-telemetry-collector/connector/sentrymetricsconnector main
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector latest

exporters:
  - gomod: github.com/Netcracker/qubership-open-telemetry-collector/exporter/logtcpexporter main
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter latest
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter latest
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter latest
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter latest
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter latest
  - gomod: github.com/Netcracker/qubership-open-telemetry-collector/exporter/graylogexporter c5f3469e533e0a1a75a7f8409e65940647fcfbff

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension latest
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension latest

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor latest
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor latest
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor latest
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor latest
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor latest
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/logdedupprocessor latest

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider latest
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider latest
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider latest
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider latest
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider latest

receivers:
  - gomod: github.com/Netcracker/qubership-open-telemetry-collector/receiver/sentryreceiver main
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver latest
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver latest
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver latest
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusremotewritereceiver latest
